apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - name: api-demo
        image: ghcr.io/dsanchor/demo-copilot-2401/demo2401:#TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: api-demo