name: Build and Publish Docker

on:
  push:
    branches:
      - main

env:
  AKS_RG: aks-demo-alb-rg
  AKS_NAME: demo
  NAMESPACE: demobankinter

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OpenJDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/api-demo:${{ github.sha }}

      - name: Log in Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ env.AKS_RG }} --name ${{ env.AKS_NAME }}

      - name: Replace #TAG in application.yaml
        run: sed -i 's/#TAG/${{ github.sha }}/g' k8s/application.yaml

      - name: Deploy to AKS
        run: kubectl apply -f k8s/application.yaml -n ${{ env.NAMESPACE }}
